//! `knack introspect` — emit the full command tree as JSON.
//!
//! The agent ergonomic the §E6 spec asks for in spirit: a single offline call
//! that lists every subcommand, flag, and exit code so an LLM can target the
//! CLI without scraping `--help` text. Always JSON; the `--json` global flag
//! is honored by the wrapper but the human path is the same JSON pretty-
//! printed (no separate text rendering — there is no good text rendering of a
//! command tree, and humans should run `knack docs commands`).

use clap::{Args, FromArgMatches, Subcommand};
use serde_json::{json, Value};

use crate::errors::CliResult;
use crate::output::{OutputMode, SCHEMA};

// Silence unused-trait-import warnings: FromArgMatches is needed transitively
// by the derive on Command for `augment_subcommands` to compile under some
// clap minor versions; importing it explicitly keeps things robust.
#[allow(dead_code)]
fn _force_use<T: FromArgMatches>() {}

#[derive(Debug, Args)]
pub struct IntrospectArgs {}

pub fn run(_args: IntrospectArgs, mode: OutputMode) -> CliResult<()> {
    let root = build_root_command();
    let payload = json!({
        "$schema": SCHEMA,
        "name": "knack",
        "version": env!("CARGO_PKG_VERSION"),
        "global_flags": describe_args(&augmented_global_args()),
        "commands": describe_subcommands(&root),
        "exit_codes": exit_codes(),
    });

    let rendered = if mode.json {
        serde_json::to_string(&payload)?
    } else if console::Term::stdout().features().is_attended() {
        serde_json::to_string_pretty(&payload)?
    } else {
        serde_json::to_string(&payload)?
    };
    println!("{rendered}");
    Ok(())
}

fn build_root_command() -> clap::Command {
    let base = clap::Command::new("knack")
        .version(env!("CARGO_PKG_VERSION"))
        .about("Teach the AI your job. Once.");
    let base = crate::commands::GlobalArgs::augment_args(base);
    crate::commands::Command::augment_subcommands(base)
}

fn augmented_global_args() -> clap::Command {
    let base = clap::Command::new("knack");
    crate::commands::GlobalArgs::augment_args(base)
}

fn describe_subcommands(cmd: &clap::Command) -> Value {
    let mut out = serde_json::Map::new();
    for sub in cmd.get_subcommands() {
        let name = sub.get_name();
        if name == "help" {
            // Auto-generated by clap — no value to introspect.
            continue;
        }
        out.insert(name.to_string(), describe_command(sub));
    }
    Value::Object(out)
}

fn describe_command(cmd: &clap::Command) -> Value {
    let about = cmd.get_about().map(|s| s.to_string()).unwrap_or_default();
    let subs = describe_subcommands(cmd);
    let flags = describe_args(cmd);
    json!({
        "about": about,
        "flags": flags,
        "subcommands": subs,
    })
}

fn describe_args(cmd: &clap::Command) -> Value {
    let mut out = Vec::new();
    for arg in cmd.get_arguments() {
        if arg.is_hide_set() {
            continue;
        }
        let name = arg.get_id().as_str();
        let long = arg.get_long().map(|s| format!("--{s}"));
        let short = arg.get_short().map(|c| format!("-{c}"));
        let help = arg.get_help().map(|s| s.to_string()).unwrap_or_default();
        let takes_value = !matches!(
            arg.get_action(),
            clap::ArgAction::SetTrue | clap::ArgAction::SetFalse
        );
        let possible_values: Vec<String> = arg
            .get_possible_values()
            .iter()
            .map(|p| p.get_name().to_string())
            .collect();
        let env = arg.get_env().map(|s| s.to_string_lossy().to_string());

        out.push(json!({
            "name": name,
            "long": long,
            "short": short,
            "help": help,
            "takes_value": takes_value,
            "possible_values": possible_values,
            "env": env,
            "required": arg.is_required_set(),
            "global": arg.is_global_set(),
        }));
    }
    Value::Array(out)
}

fn exit_codes() -> Value {
    use crate::errors::ExitCode;
    json!([
        { "code": ExitCode::SUCCESS.0, "name": "SUCCESS", "description": "success" },
        { "code": ExitCode::USER.0, "name": "USER", "description": "user error (bad args, not found)" },
        { "code": ExitCode::AUTH.0, "name": "AUTH", "description": "auth error (not logged in / token expired)" },
        { "code": ExitCode::NETWORK.0, "name": "NETWORK", "description": "network or API error" },
        { "code": ExitCode::CONFLICT.0, "name": "CONFLICT", "description": "conflict (publish needs --force)" },
        { "code": ExitCode::PLAN.0, "name": "PLAN", "description": "plan limit (free tier hit cap)" },
        { "code": ExitCode::USAGE.0, "name": "USAGE", "description": "invalid input (POSIX EX_USAGE)" },
        { "code": ExitCode::INTERNAL.0, "name": "INTERNAL", "description": "internal CLI bug" },
    ])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exit_codes_table_complete() {
        let codes = exit_codes();
        let arr = codes.as_array().unwrap();
        // Ensure every documented variant is present.
        let names: Vec<&str> = arr.iter().map(|v| v["name"].as_str().unwrap()).collect();
        for expected in [
            "SUCCESS", "USER", "AUTH", "NETWORK", "CONFLICT", "PLAN", "USAGE", "INTERNAL",
        ] {
            assert!(names.contains(&expected), "missing {expected}");
        }
    }

    #[test]
    fn root_command_has_all_subcommands() {
        let root = build_root_command();
        let names: Vec<&str> = root.get_subcommands().map(|s| s.get_name()).collect();
        for expected in [
            "auth", "list", "pull", "diff", "edit", "publish", "run", "mark", "docs",
        ] {
            assert!(names.contains(&expected), "missing subcommand {expected}");
        }
    }

    #[test]
    fn auth_subcommand_has_login_logout_status() {
        let root = build_root_command();
        let auth = root.find_subcommand("auth").unwrap();
        let names: Vec<&str> = auth.get_subcommands().map(|s| s.get_name()).collect();
        assert!(names.contains(&"login"));
        assert!(names.contains(&"logout"));
        assert!(names.contains(&"status"));
    }
}
