//! Subcommand definitions + dispatch.

pub mod auth;
pub mod completions;
pub mod debug;
pub mod diff;
pub mod docs;
pub mod edit;
pub mod interview;
pub mod introspect;
pub mod list;
pub mod mark;
pub mod publish;
pub mod pull;
pub mod run;

use std::sync::Arc;

use clap::{Args, Subcommand};

use crate::api::ApiClient;
use crate::auth_store::{KeyringStore, TokenStore};
use crate::config::Config;
use crate::errors::CliResult;
use crate::output::OutputMode;

/// Top-level subcommands. `clap`'s derive emits the help/usage strings so the
/// `commands.md` doc topic can be regenerated by `knack help --json`.
#[derive(Debug, Subcommand)]
pub enum Command {
    /// Sign in / out / show current account
    #[command(subcommand)]
    Auth(auth::AuthCmd),

    /// List skills you can read
    List(list::ListArgs),

    /// Pull a skill folder to disk
    Pull(pull::PullArgs),

    /// Diff two versions of a skill (or local vs cloud)
    Diff(diff::DiffArgs),

    /// Open a skill's SKILL.md in $EDITOR; on save, push as a new version
    Edit(edit::EditArgs),

    /// Bump the semver and push the local skill folder
    Publish(publish::PublishArgs),

    /// Execute a skill against a fresh input
    Run(run::RunArgs),

    /// Mark a run succeeded / failed (closes the agent loop)
    Mark(mark::MarkArgs),

    /// Print embedded docs (offline)
    Docs(docs::DocsArgs),

    /// CLI-native interview that drives the conductor end-to-end
    Interview(interview::InterviewArgs),

    /// Emit the full command tree as JSON (agent introspection)
    Introspect(introspect::IntrospectArgs),

    /// Emit a shell completion script to stdout
    Completions(completions::CompletionsArgs),

    /// Print env / config / auth state for bug reports
    Debug(debug::DebugArgs),
}

/// Cross-cutting flags every subcommand inherits.
#[derive(Debug, Clone, Args)]
pub struct GlobalArgs {
    /// Print machine-readable JSON to stdout instead of human-friendly text.
    #[arg(long, global = true)]
    pub json: bool,

    /// Suppress all human-readable progress output. Errors still printed.
    #[arg(long, global = true)]
    pub quiet: bool,

    /// Disable ANSI color even on a TTY.
    #[arg(long, global = true)]
    pub no_color: bool,

    /// Bypass the keyring and use this access token. Useful for CI / containers.
    #[arg(long, global = true, env = "KNACK_AUTH_TOKEN")]
    pub auth_token: Option<String>,

    /// Profile name in the keyring. Lets you keep work + personal logged in
    /// at the same time.
    #[arg(long, global = true, default_value = "default")]
    pub account: String,
}

impl GlobalArgs {
    pub fn output_mode(&self) -> OutputMode {
        OutputMode {
            json: self.json,
            quiet: self.quiet,
            no_color: self.no_color || self.json,
        }
    }
}

/// Build the API client from CLI flags and config. Tests can construct one
/// directly with a `MemoryStore`; this is the production path.
pub fn build_client(config: Config, args: &GlobalArgs) -> ApiClient {
    let store: Arc<dyn TokenStore + Send + Sync> =
        Arc::new(KeyringStore::new(config.keyring_service.clone()));
    ApiClient::new(config, store, args.account.clone())
        .with_bearer_override(args.auth_token.clone())
}

/// Dispatch a parsed command to its handler.
pub async fn dispatch(cmd: Command, client: ApiClient, mode: OutputMode) -> CliResult<()> {
    match cmd {
        Command::Auth(c) => auth::run(c, client, mode).await,
        Command::List(a) => list::run(a, client, mode).await,
        Command::Pull(a) => pull::run(a, client, mode).await,
        Command::Diff(a) => diff::run(a, client, mode).await,
        Command::Edit(a) => edit::run(a, client, mode).await,
        Command::Publish(a) => publish::run(a, client, mode).await,
        Command::Run(a) => run::run(a, client, mode).await,
        Command::Mark(a) => mark::run(a, client, mode).await,
        Command::Docs(a) => docs::run(a, mode),
        Command::Interview(a) => interview::run(a, client, mode).await,
        Command::Introspect(a) => introspect::run(a, mode),
        Command::Completions(a) => completions::run(a, mode),
        Command::Debug(a) => debug::run(a, client, mode),
    }
}
