//! Subcommand definitions + dispatch.

pub mod auth;
pub mod completions;
pub mod create;
pub mod debug;
pub mod diff;
pub mod docs;
pub mod edit;
pub mod feedback;
pub mod folder;
pub mod fork;
pub mod info;
pub mod init;
pub mod install;
pub mod introspect;
pub mod list;
pub mod mark;
pub mod publish;
pub mod pull;
pub mod rate;
pub mod run;
pub mod search;
pub mod sync;
pub mod team;
pub mod username;
pub mod validate;

use std::sync::Arc;

use clap::{Args, Subcommand};

use crate::api::ApiClient;
use crate::auth_store::{KeyringStore, TokenStore};
use crate::config::Config;
use crate::errors::CliResult;
use crate::output::OutputMode;

/// Top-level subcommands. `clap`'s derive emits the help/usage strings so the
/// `commands.md` doc topic can be regenerated by `knack help --json`.
#[derive(Debug, Subcommand)]
pub enum Command {
    /// Sign in / out / show current account
    #[command(subcommand)]
    Auth(auth::AuthCmd),

    /// List skills you can read
    List(list::ListArgs),

    /// Pull a skill folder to disk. Accepts `<slug>`, `<slug>@<semver>`,
    /// `@<author>/<slug>`, or `@<author>/<slug>@<semver>`.
    Pull(pull::PullArgs),

    /// Diff two versions of a skill (or local vs cloud)
    Diff(diff::DiffArgs),

    /// Create a new skill shell (slug + name + scope). Run `knack publish` after.
    Create(create::CreateArgs),

    /// Update a skill's name, description, or scope. Slug is immutable.
    Edit(edit::EditArgs),

    /// Bump the semver and push the local skill folder
    Publish(publish::PublishArgs),

    /// Fork a public marketplace skill into your library. Server-side
    /// copy of the latest version; pulls into `drafts/<slug>/` for edit.
    Fork(fork::ForkArgs),

    /// Execute a skill against a fresh input
    Run(run::RunArgs),

    /// Mark a run succeeded / failed (closes the agent loop)
    Mark(mark::MarkArgs),

    /// Print embedded docs (offline)
    Docs(docs::DocsArgs),

    /// Emit the full command tree as JSON (agent introspection)
    Introspect(introspect::IntrospectArgs),

    /// Emit a shell completion script to stdout
    Completions(completions::CompletionsArgs),

    /// Print env / config / auth state for bug reports
    Debug(debug::DebugArgs),

    /// Register knack with the AI agent on this machine (Claude Code, Codex, Cursor, ...)
    Install(install::InstallArgs),

    /// Scaffold a workspace-local `.knack/` (skills/, drafts/, .gitignore, README).
    Init(init::InitArgs),

    /// Print the canonical Knack agent playbook (agent.txt). Offline-fallback bundled.
    Info(info::InfoArgs),

    /// Local pre-flight check on a skill folder. Catches missing required
    /// meta.knack.yaml / SKILL.md fields before you pay a publish round-trip.
    Validate(validate::ValidateArgs),

    /// Claim a marketplace username (one-time). Required to publish public skills.
    Username(username::UsernameArgs),

    /// Search the public marketplace by keyword
    Search(search::SearchArgs),

    /// Rate a public skill (1-5 stars). Pass --clear to remove your rating.
    Rate(rate::RateArgs),

    /// Refresh per-skill agent shims (Claude SKILL.md, Cursor .mdc, AGENTS.md blocks).
    /// Runs automatically after `pull` / `publish`; this command is for manual recovery.
    Sync(sync::SyncArgs),

    /// Team management: create / list / show / invite / accept / role
    #[command(subcommand)]
    Team(team::TeamCmd),

    /// Folder management: organize personal and team skills into folders.
    /// Public/marketplace skills are not foldered.
    #[command(subcommand)]
    Folder(folder::FolderCmd),

    /// Send a bug report or follow up on Knack staff's reply.
    /// Threads are visible to both the user (in the web UI) and to
    /// agents calling from this account's CLI.
    #[command(subcommand)]
    Feedback(feedback::FeedbackCmd),
}

/// Cross-cutting flags every subcommand inherits.
#[derive(Debug, Clone, Args)]
pub struct GlobalArgs {
    /// Print machine-readable JSON to stdout instead of human-friendly text.
    #[arg(long, global = true)]
    pub json: bool,

    /// Suppress all human-readable progress output. Errors still printed.
    #[arg(long, global = true)]
    pub quiet: bool,

    /// Disable ANSI color even on a TTY.
    #[arg(long, global = true)]
    pub no_color: bool,

    /// Bypass the keyring and use this access token. Useful for CI / containers.
    #[arg(long, global = true, env = "KNACK_AUTH_TOKEN")]
    pub auth_token: Option<String>,

    /// Profile name in the keyring. Lets you keep work + personal logged in
    /// at the same time.
    #[arg(long, global = true, default_value = "default")]
    pub account: String,
}

impl GlobalArgs {
    pub fn output_mode(&self) -> OutputMode {
        OutputMode {
            json: self.json,
            quiet: self.quiet,
            no_color: self.no_color || self.json,
        }
    }
}

/// Build the API client from CLI flags and config. Tests can construct one
/// directly with a `MemoryStore`; this is the production path.
pub fn build_client(config: Config, args: &GlobalArgs) -> ApiClient {
    let store: Arc<dyn TokenStore + Send + Sync> =
        Arc::new(KeyringStore::new(config.keyring_service.clone()));
    ApiClient::new(config, store, args.account.clone())
        .with_bearer_override(args.auth_token.clone())
}

/// Dispatch a parsed command to its handler.
pub async fn dispatch(cmd: Command, client: ApiClient, mode: OutputMode) -> CliResult<()> {
    match cmd {
        Command::Auth(c) => auth::run(c, client, mode).await,
        Command::List(a) => list::run(a, client, mode).await,
        Command::Pull(a) => pull::run(a, client, mode).await,
        Command::Diff(a) => diff::run(a, client, mode).await,
        Command::Create(a) => create::run(a, client, mode).await,
        Command::Edit(a) => edit::run(a, client, mode).await,
        Command::Publish(a) => publish::run(a, client, mode).await,
        Command::Fork(a) => fork::run(a, client, mode).await,
        Command::Run(a) => run::run(a, client, mode).await,
        Command::Mark(a) => mark::run(a, client, mode).await,
        Command::Docs(a) => docs::run(a, mode),
        Command::Introspect(a) => introspect::run(a, mode),
        Command::Completions(a) => completions::run(a, mode),
        Command::Debug(a) => debug::run(a, client, mode),
        Command::Install(a) => install::run(a, mode),
        Command::Init(a) => init::run(a, mode),
        Command::Info(a) => info::run(a, mode).await,
        Command::Validate(a) => validate::run(a, mode),
        Command::Username(a) => username::run(a, client, mode).await,
        Command::Search(a) => search::run(a, client, mode).await,
        Command::Rate(a) => rate::run(a, client, mode).await,
        Command::Sync(a) => sync::run(a, client.config, mode),
        Command::Team(c) => team::run(c, client, mode).await,
        Command::Folder(c) => folder::run(c, client, mode).await,
        Command::Feedback(c) => feedback::run(c, client, mode).await,
    }
}
