//! Subcommand definitions + dispatch.

pub mod auth;
pub mod completions;
pub mod create;
pub mod debug;
pub mod diff;
pub mod docs;
pub mod edit;
pub mod export;
pub mod feedback;
pub mod folder;
pub mod fork;
pub mod info;
pub mod info_chunks;
pub mod init;
pub mod install;
pub mod interview;
pub mod introspect;
pub mod link;
pub mod list;
pub mod mark;
pub mod publish;
pub mod pull;
pub mod rate;
pub mod run;
pub mod runs;
pub mod search;
pub mod sync;
pub mod team;
pub mod uninstall;
pub mod upgrade;
pub mod username;
pub mod validate;

use std::path::PathBuf;
use std::sync::Arc;

use clap::{Args, Subcommand};

use crate::api::ApiClient;
use crate::auth_store::{FileStore, KeyringStore, TokenStore};
use crate::config::Config;
use crate::errors::CliResult;
use crate::output::OutputMode;

/// Top-level subcommands. `clap`'s derive emits the help/usage strings so the
/// `commands.md` doc topic can be regenerated by `knack help --json`.
#[derive(Debug, Subcommand)]
pub enum Command {
    /// Sign in / out / show current account
    #[command(subcommand)]
    Auth(auth::AuthCmd),

    /// List skills you can read
    List(list::ListArgs),

    /// Pull a skill folder to disk. Accepts `<slug>`, `<slug>@<semver>`,
    /// `@<author>/<slug>`, or `@<author>/<slug>@<semver>`.
    Pull(pull::PullArgs),

    /// Install a skill as a native `/<slug>` slash command in every agent
    /// on this machine (telemetry-preserving). `--global` (default) / `--local`.
    Link(link::LinkArgs),

    /// Remove a linked skill's slash command from agent skill directories.
    Unlink(link::UnlinkArgs),

    /// Bulk export every skill the caller can read to a local directory.
    /// Cloud-only meaningful surface; self-host just points at your clone.
    Export(export::ExportArgs),

    /// Diff two versions of a skill (or local vs cloud)
    Diff(diff::DiffArgs),

    /// Create a new skill shell (slug + name + scope). Run `knack publish` after.
    Create(create::CreateArgs),

    /// Update a skill's name, description, or scope. Slug is immutable.
    Edit(edit::EditArgs),

    /// Bump the semver and push the local skill folder
    Publish(publish::PublishArgs),

    /// Fork a public marketplace skill into your library. Server-side
    /// copy of the latest version; pulls into `drafts/<slug>/` for edit.
    Fork(fork::ForkArgs),

    /// Execute a skill against a fresh input
    Run(run::RunArgs),

    /// Mark a run succeeded / failed (closes the agent loop)
    Mark(mark::MarkArgs),

    /// Analyze past runs: list / show / stats / diff across versions
    #[command(subcommand)]
    Runs(runs::RunsCmd),

    /// Print embedded docs (offline)
    Docs(docs::DocsArgs),

    /// Emit the full command tree as JSON (agent introspection)
    Introspect(introspect::IntrospectArgs),

    /// Emit a shell completion script to stdout
    Completions(completions::CompletionsArgs),

    /// Print env / config / auth state for bug reports
    Debug(debug::DebugArgs),

    /// Register knack with the AI agent on this machine (Claude Code, Codex, Cursor, ...)
    Install(install::InstallArgs),

    /// Reverse install: strip shim blocks, clear auth, point at the
    /// platform script for binary removal. Pass `--script` to print the
    /// one-liner for full removal without self-replace concerns.
    Uninstall(uninstall::UninstallArgs),

    /// Upgrade knack to the latest version via the platform install
    /// script. Self-replaces on macOS/Linux; on Windows prints the
    /// one-liner to run in a fresh shell.
    Upgrade(upgrade::UpgradeArgs),

    /// Scaffold a workspace-local `.knack/` (skills/, drafts/, .gitignore, README).
    Init(init::InitArgs),

    /// Agent-driven skill authoring. The agent runs the 6-phase interview;
    /// this command writes the interview skill into the project and persists
    /// session state between turns.
    Interview(interview::InterviewArgs),

    /// Print the canonical Knack agent playbook (agent.txt), whole or by
    /// section. `knack info --list` for the index, `knack info <slug>...` for
    /// specific sections. Offline-fallback bundled.
    Info(info::InfoArgs),

    /// Local pre-flight check on a skill folder. Catches missing required
    /// meta.knack.yaml / SKILL.md fields before you pay a publish round-trip.
    Validate(validate::ValidateArgs),

    /// Claim a marketplace username (one-time). Required to publish public skills.
    Username(username::UsernameArgs),

    /// Search the public marketplace by keyword
    Search(search::SearchArgs),

    /// Rate a public skill (1-5 stars). Pass --clear to remove your rating.
    Rate(rate::RateArgs),

    /// Refresh per-skill agent shims (Claude SKILL.md, Cursor .mdc, AGENTS.md blocks).
    /// Runs automatically after `pull` / `publish`; this command is for manual recovery.
    Sync(sync::SyncArgs),

    /// Team management: create / list / show / invite / accept / role
    #[command(subcommand)]
    Team(team::TeamCmd),

    /// Folder management: organize personal and team skills into folders.
    /// Public/marketplace skills are not foldered.
    #[command(subcommand)]
    Folder(folder::FolderCmd),

    /// Send a bug report or follow up on Knack staff's reply.
    /// Threads are visible to both the user (in the web UI) and to
    /// agents calling from this account's CLI.
    #[command(subcommand)]
    Feedback(feedback::FeedbackCmd),
}

/// Cross-cutting flags every subcommand inherits.
#[derive(Debug, Clone, Args)]
pub struct GlobalArgs {
    /// Print machine-readable JSON to stdout instead of human-friendly text.
    #[arg(long, global = true)]
    pub json: bool,

    /// Suppress all human-readable progress output. Errors still printed.
    #[arg(long, global = true)]
    pub quiet: bool,

    /// Disable ANSI color even on a TTY.
    #[arg(long, global = true)]
    pub no_color: bool,

    /// Bypass the keyring and use this access token. Useful for CI / containers.
    #[arg(long, global = true, env = "KNACK_AUTH_TOKEN")]
    pub auth_token: Option<String>,

    /// Profile name in the keyring. Lets you keep work + personal logged in
    /// at the same time.
    #[arg(long, global = true, default_value = "default")]
    pub account: String,

    /// Trust an extra PEM CA bundle on top of the system + bundled roots.
    /// For corporate TLS-inspecting proxies whose CA isn't in the OS
    /// keychain. Also via KNACK_CA_BUNDLE or the standard SSL_CERT_FILE.
    #[arg(long, global = true, value_name = "FILE")]
    pub cacert: Option<PathBuf>,

    /// Skip TLS certificate verification entirely. Last-resort escape
    /// hatch for broken corporate proxies; prefer --cacert. Also via
    /// KNACK_INSECURE=1.
    #[arg(long, global = true)]
    pub insecure: bool,
}

impl GlobalArgs {
    pub fn output_mode(&self) -> OutputMode {
        OutputMode {
            json: self.json,
            quiet: self.quiet,
            no_color: self.no_color || self.json,
        }
    }
}

/// Build the API client from CLI flags and config. Tests can construct
/// one directly with a `MemoryStore`; this is the production path.
///
/// Primary store: file at `~/.knack/auth.json` (post-0.5 default).
/// Legacy fallback: OS keyring, consulted only when the file is empty so
/// pre-0.5 users keep working until they re-run `knack auth login`.
pub fn build_client(config: Config, args: &GlobalArgs) -> ApiClient {
    let store: Arc<dyn TokenStore + Send + Sync> = match FileStore::from_default_path() {
        Some(fs) => Arc::new(fs),
        // Falls through to keyring as primary on systems where no home
        // dir resolves — vanishingly rare in practice.
        None => Arc::new(KeyringStore::new(config.keyring_service.clone())),
    };
    let legacy: Arc<dyn TokenStore + Send + Sync> =
        Arc::new(KeyringStore::new(config.keyring_service.clone()));
    ApiClient::new(config, store, args.account.clone())
        .with_legacy_store(Some(legacy))
        .with_bearer_override(args.auth_token.clone())
}

/// Dispatch a parsed command to its handler.
pub async fn dispatch(cmd: Command, client: ApiClient, mode: OutputMode) -> CliResult<()> {
    match cmd {
        Command::Auth(c) => auth::run(c, client, mode).await,
        Command::List(a) => list::run(a, client, mode).await,
        Command::Pull(a) => pull::run(a, client, mode).await,
        Command::Link(a) => link::run_link(a, client, mode).await,
        Command::Unlink(a) => link::run_unlink(a, client, mode).await,
        Command::Export(a) => export::run(a, client, mode).await,
        Command::Diff(a) => diff::run(a, client, mode).await,
        Command::Create(a) => create::run(a, client, mode).await,
        Command::Edit(a) => edit::run(a, client, mode).await,
        Command::Publish(a) => publish::run(a, client, mode).await,
        Command::Fork(a) => fork::run(a, client, mode).await,
        Command::Run(a) => run::run(a, client, mode).await,
        Command::Mark(a) => mark::run(a, client, mode).await,
        Command::Runs(c) => runs::run(c, client, mode).await,
        Command::Docs(a) => docs::run(a, mode),
        Command::Introspect(a) => introspect::run(a, mode),
        Command::Completions(a) => completions::run(a, mode),
        Command::Debug(a) => debug::run(a, client, mode).await,
        Command::Install(a) => install::run(a, mode),
        Command::Uninstall(a) => uninstall::run(a, client, mode).await,
        Command::Upgrade(a) => upgrade::run(a, mode),
        Command::Init(a) => init::run(a, mode),
        Command::Interview(a) => interview::run(a, mode).await,
        Command::Info(a) => info::run(a, mode).await,
        Command::Validate(a) => validate::run(a, mode),
        Command::Username(a) => username::run(a, client, mode).await,
        Command::Search(a) => search::run(a, client, mode).await,
        Command::Rate(a) => rate::run(a, client, mode).await,
        Command::Sync(a) => sync::run(a, client.config, mode),
        Command::Team(c) => team::run(c, client, mode).await,
        Command::Folder(c) => folder::run(c, client, mode).await,
        Command::Feedback(c) => feedback::run(c, client, mode).await,
    }
}
